version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Маппинг локального порта 8080 на порт контейнера
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: onlinebooking
      DB_PORT: 5432
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: tauasardinmukhammed@gmail.com
      EMAIL_PASSWORD: jozghbyeljrmhjwq
      JWT_SECRET: s3cr3tK3yG3n3r4t3dByOp3nSSL
      GITHUB_CLIENT_ID: Ov23li3nsJgkWrr1piKx
      GITHUB_CLIENT_SECRET: e8d2c54daa78da6fa8cd01806cd3090a595010cd
      GITHUB_REDIRECT_URL: http://localhost:8080/auth/github/callback
      SESSION_SECRET: 4b8e4d8a6e0c7b5d3f9c1a2b4f6e8d7c0b1a9e3f5c7d6e8f4b3a2c5d7e9f0a1b
      DATABASE_URL: postgres://postgres:1234@db:5432/onlinebooking
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: onlinebooking
    ports:
      - "5432:5432" # Маппинг порта для базы данных
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
